import { PainterStyle, Language } from './types';

export const PAINTER_STYLES: PainterStyle[] = [
  { id: 'van-gogh', name: 'Vincent van Gogh', palette: ['#1d2d50', '#fcd34d', '#2563eb', '#f59e0b', '#ffffff'], vibe: 'Swirling energy', description: 'Starry Night Blues & Yellows' },
  { id: 'monet', name: 'Claude Monet', palette: ['#e0f2fe', '#7dd3fc', '#86efac', '#f0abfc', '#1e293b'], vibe: 'Impressionist calm', description: 'Water Lilies Pastels' },
  { id: 'dali', name: 'Salvador Dalí', palette: ['#451a03', '#d97706', '#fca5a5', '#fbbf24', '#ffffff'], vibe: 'Surrealist melt', description: 'Desert Time Distortion' },
  { id: 'picasso', name: 'Pablo Picasso', palette: ['#7f1d1d', '#f87171', '#fbbf24', '#1e3a8a', '#ffffff'], vibe: 'Cubist geometry', description: 'Abstract Shapes & Faces' },
  { id: 'warhol', name: 'Andy Warhol', palette: ['#ec4899', '#facc15', '#22d3ee', '#000000', '#ffffff'], vibe: 'Pop Art contrast', description: 'Vibrant Screen Print' },
  { id: 'da-vinci', name: 'Leonardo da Vinci', palette: ['#3f2e18', '#a89f91', '#d4c5b0', '#78350f', '#fffbeb'], vibe: 'Renaissance sketch', description: 'Sepia Parchment' },
  { id: 'hokusai', name: 'Hokusai', palette: ['#fff7ed', '#1e3a8a', '#60a5fa', '#94a3b8', '#0f172a'], vibe: 'Ukiyo-e wave', description: 'Great Wave Blue' },
  { id: 'klimt', name: 'Gustav Klimt', palette: ['#422006', '#eab308', '#ca8a04', '#14532d', '#ffffff'], vibe: 'Golden decorative', description: 'The Kiss Gold Leaf' },
  { id: 'munch', name: 'Edvard Munch', palette: ['#450a0a', '#c2410c', '#1e293b', '#f97316', '#ffffff'], vibe: 'Expressionist scream', description: 'Emotional Sunset' },
  { id: 'pollock', name: 'Jackson Pollock', palette: ['#f3f4f6', '#000000', '#ef4444', '#facc15', '#1f2937'], vibe: 'Action drip', description: 'Chaos Splatter' },
  { id: 'kahlo', name: 'Frida Kahlo', palette: ['#064e3b', '#ef4444', '#f472b6', '#166534', '#ffffff'], vibe: 'Folk surrealism', description: 'Vibrant Mexican Flora' },
  { id: 'rembrandt', name: 'Rembrandt', palette: ['#000000', '#451a03', '#b45309', '#fef3c7', '#ffffff'], vibe: 'Chiaroscuro', description: 'Shadow & Light' },
  { id: 'okeeffe', name: 'Georgia O\'Keeffe', palette: ['#fff1f2', '#f43f5e', '#fb7185', '#fda4af', '#881337'], vibe: 'Modernist macro', description: 'Large Flower Close-up' },
  { id: 'basquiat', name: 'Jean-Michel Basquiat', palette: ['#000000', '#ef4444', '#facc15', '#3b82f6', '#ffffff'], vibe: 'Neo-expressionist graffiti', description: 'Crowns & Skulls' },
  { id: 'matisse', name: 'Henri Matisse', palette: ['#1e3a8a', '#ef4444', '#22c55e', '#facc15', '#ffffff'], vibe: 'Fauvist cut-outs', description: 'Dancing Colors' },
  { id: 'vermeer', name: 'Johannes Vermeer', palette: ['#0f172a', '#1d4ed8', '#facc15', '#cbd5e1', '#ffffff'], vibe: 'Dutch light', description: 'Pearl Earring Blue' },
  { id: 'hopper', name: 'Edward Hopper', palette: ['#0f172a', '#10b981', '#ef4444', '#e2e8f0', '#ffffff'], vibe: 'Realist solitude', description: 'Nighthawks Diner' },
  { id: 'kandinsky', name: 'Wassily Kandinsky', palette: ['#ffffff', '#000000', '#ef4444', '#3b82f6', '#facc15'], vibe: 'Geometric abstract', description: 'Composition VIII' },
  { id: 'magritte', name: 'René Magritte', palette: ['#60a5fa', '#ffffff', '#16a34a', '#000000', '#1e293b'], vibe: 'Surrealist wit', description: 'Bowler Hat & Apple' },
  { id: 'renoir', name: 'Pierre-Auguste Renoir', palette: ['#fdf2f8', '#f9a8d4', '#86efac', '#fcd34d', '#4a044e'], vibe: 'Luminous impressionism', description: 'Luncheon Party' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    title: 'Enterprise Document & Data Platform',
    dashboard: 'Dashboard',
    features: 'AI Studio',
    settings: 'Settings',
    style: 'Current Style',
    spin: 'SPIN JACKPOT',
    light: 'Light',
    dark: 'Dark',
    welcome: 'Welcome back, Architect.',
    activeDocs: 'Active Documents',
    procTime: 'Avg. Processing Time',
    sysHealth: 'System Health',
    feature1: 'Deep-Dream Summarizer',
    feature2: 'Sentiment Symphony',
    feature3: 'Predictive Data Sculpture',
    feature4: 'Polyglot Synthesis',
    feature5: 'Smart Redaction Gallery',
    processing: 'AI Muse is thinking...',
    result: 'Artistic Output',
    upload: 'Upload Document (PDF)',
    runAi: 'Generate Art',
    promptPlaceholder: 'Enter your text or data context here...',
  },
  'zh-TW': {
    title: '企業文檔與數據藝術平台',
    dashboard: '儀表板',
    features: 'AI 工作室',
    settings: '設置',
    style: '當前風格',
    spin: '風格老虎機',
    light: '亮色',
    dark: '暗色',
    welcome: '歡迎回來，架構師。',
    activeDocs: '活躍文檔',
    procTime: '平均處理時間',
    sysHealth: '系統健康度',
    feature1: '深夢摘要生成器',
    feature2: '情感交響曲',
    feature3: '預測數據雕塑',
    feature4: '多語言合成',
    feature5: '智能藝術遮罩',
    processing: 'AI 繆斯正在思考...',
    result: '藝術產出',
    upload: '上傳文檔 (PDF)',
    runAi: '生成藝術',
    promptPlaceholder: '在此輸入您的文本或數據背景...',
  }
};
